spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: sentinel-api
sentinel:
  conversation:
    import:
      directory: ${user.home}/import/

logging:
  level: TRACE
